#!/bin/bash
folderSystem="/System/Library/PrivateFrameworks/MobileActivation.framework/Support/Certificates";
folderDaemon="/System/Library/LaunchDaemons";
folder="/Users/$(whoami)/Desktop/tmp";
folderBin="$Folder/libs";
Center="/./private/var/wireless/Library/Preferences/com.apple.commcenter.device_specific_nobackup.plist";
iTunes="iTunes_Control/iTunes";
Mobile="/./private/var/mobile";
$folderBin/idevicepair pair;
folderBackup="/Users/$(whoami)/Desktop/Backups_iOS14/$(/Users/$(whoami)/Desktop/tmp/libs/idevice_id -l)";
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'mount -o rw,union,update /';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' scp -P 2222 -p "$folderBackup"/Backup.tar root@localhost:"/./Backup.tar";
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chflags -R nouchg /private/var/wireless/Library/Preferences/ /private/var/containers/Data/System/*/Library/internal/../*';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'launchctl unload '$folderDaemon'/com.apple.mobileactivationd.plist';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'launchctl unload '$folderDaemon'/com.apple.CommCenter.plist';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'tar -xvf /./Backup.tar -C /./';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'rm /./Backup.tar';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'cd /private/var/containers/Data/System/*/Library/internal/../ && cp -rp /./activation_records .';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'cd /private/var/containers/Data/System/*/Library/internal/../ && cp -rp /./internal .';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'cd /private/var/containers/Data/System/*/Library/internal/../ && chflags -R uchg activation_records';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod 00600 '$Center'';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chown _wireless:_wireless '$Center'';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chflags uchg '$Center'';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod -R 755 '$Mobile'/Library/FairPlay';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chown -R mobile:mobile '$Mobile'/Library/FairPlay '$Mobile'/Media/';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod 00664 '$Mobile'/Library/FairPlay/'$iTunes'/IC-Info.sisv';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'chmod 00664 '$Mobile'/Media/'$iTunes'/IC-Info.sidv';
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'launchctl load '$folderDaemon'/com.apple.CommCenter.plist';
sleep 6;
/Users/$(whoami)/Desktop/tmp/libs/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no root@localhost -p2222 'launchctl load '$folderDaemon'/com.apple.mobileactivationd.plist';